import {
  ladakhImg,
  imgShalimar,
  imgGulmargResort,
  imgSonamargMdw,
  imgPangong,
  imgYusmarg,
  imgHouseboat,
  imgSrinagar,
  imgKokernag,
  imgVaishnoDevi,
  imgAmarnath,
  imgNubra,
  imgMagneticHill,
  imgTsoMoriri,
  imgAruValley,
  imgBetaab,
  imgKounsarnag,
  imgChandanwari,
  JKTDC_AHARBAL,
  JKTDC_PAHALGAM,
  JKTDC_DAKSUM,
  JKTDC_DOODHP,
  JKTDC_GUREZ,
  JKTDC_LOLAB,
  JKTDC_NARANAG,
  JKTDC_SINTHAN,
  JKTDC_WATLAB,
  JKTDC_PEERGALI,
  JKTDC_WARWAN,
  JKTDC_NISHAT,
  JKTDC_CHASHME,
  JKTDC_PARI,
  JKTDC_TULIP,
  JKTDC_DAL,
  JKTDC_NAGIN,
  JKTDC_VISHANSAR,
  JKTDC_KRISHNASAR,
  JKTDC_VERINAG,
  MTN1,
  MTN2,
  MTN3,
  LAKE1,
  LAKE3,
  FOR1,
  FOR3,
  GRN1,
  WILD1,
} from "@/components/destinationImages";

export type Category =
  | "All"
  | "Popular"
  | "Picnic Spots"
  | "Hill Stations"
  | "Lakes & Springs"
  | "Pilgrimages"
  | "Ladakh";

export interface Dest {
  name: string;
  tagline: string;
  desc: string;
  images: string[];
  category: Exclude<Category, "All">;
  highlight?: string;
}

export const destinations: Dest[] = [
  /* ════════════ POPULAR ════════════════════════════════════════ */
  {
    name: "Srinagar — Dal Lake",
    tagline: "City of Lakes & Gardens",
    desc: "Shikara rides, floating markets, and stunning Mughal gardens on Kashmir's iconic Dal Lake.",
    images: [JKTDC_DAL],
    category: "Popular",
    highlight: "Must Visit",
  },
  {
    name: "Gulmarg",
    tagline: "Meadow of Flowers",
    desc: "Asia's highest gondola, world-class skiing in winter, and stunning alpine meadows in summer.",
    images: [imgGulmargResort],
    category: "Popular",
    highlight: "Top Rated",
  },
  {
    name: "Pahalgam",
    tagline: "Valley of Shepherds",
    desc: "Lush river valleys, alpine meadows, and base camp for the holy Amarnath Yatra.",
    images: [JKTDC_PAHALGAM],
    category: "Popular",
  },
  {
    name: "Sonamarg",
    tagline: "Meadow of Gold",
    desc: "Golden meadows at 8,957 ft, gateway to Thajiwas Glacier and stunning alpine lakes.",
    images: [imgSonamargMdw],
    category: "Popular",
  },
  {
    name: "Dal Lake Houseboat",
    tagline: "Stay on the Lake",
    desc: "Wake up on the water in a heritage wooden houseboat with mountain views and Kashmiri kahwa.",
    images: [imgHouseboat],
    category: "Popular",
    highlight: "Unique Stay",
  },
  {
    name: "Yusmarg",
    tagline: "Meadow of Jesus",
    desc: "Pristine pine-forested meadow ideal for picnics and horse rides, far from the tourist crowds.",
    images: [imgYusmarg],
    category: "Popular",
  },
  {
    name: "Srinagar City",
    tagline: "Paradise on Earth",
    desc: "Old city mosques, spice bazaars, Dal Lake, and the stunning Badam Wari almond blossom garden.",
    images: [imgSrinagar],
    category: "Popular",
    highlight: "Must Visit",
  },

  /* ════════════ PICNIC SPOTS ═══════════════════════════════════ */
  {
    name: "Nishat Bagh",
    tagline: "Garden of Bliss",
    desc: "12-terraced Mughal garden on Dal Lake with roses, fountains, and Himalayan views.",
    images: [JKTDC_NISHAT],
    category: "Picnic Spots",
  },
  {
    name: "Shalimar Bagh",
    tagline: "Abode of Love",
    desc: "Emperor Jahangir's love garden — chinar trees, cascading fountains on the shores of Dal Lake.",
    images: [imgShalimar],
    category: "Picnic Spots",
  },
  {
    name: "Tulip Garden",
    tagline: "Asia's Largest Tulip Garden",
    desc: "1.5 million tulips in 64 varieties bloom every spring against the Zabarwan hills.",
    images: [JKTDC_TULIP],
    category: "Picnic Spots",
    highlight: "Spring Special",
  },
  {
    name: "Chashme Shahi",
    tagline: "Royal Spring",
    desc: "Hilltop Mughal garden fed by a sacred spring with panoramic views of Dal Lake.",
    images: [JKTDC_CHASHME],
    category: "Picnic Spots",
  },
  {
    name: "Betaab Valley",
    tagline: "Bollywood's Favourite Valley",
    desc: "Lush Bollywood valley with crystal streams and colourful meadows, 15 km from Pahalgam.",
    images: [imgBetaab],
    category: "Picnic Spots",
    highlight: "Film Location",
  },
  {
    name: "Aru Valley",
    tagline: "Pristine Alpine Meadows",
    desc: "Quiet alpine pastures and shepherd huts, trailhead for the Kolhoi Glacier trek.",
    images: [imgAruValley],
    category: "Picnic Spots",
  },
  {
    name: "Harwan Garden",
    tagline: "Ancient Buddhist Retreat",
    desc: "Ancient Buddhist relics, trout hatchery, and forest trails along a mountain stream.",
    images: [FOR1],
    category: "Picnic Spots",
  },
  {
    name: "Pari Mahal",
    tagline: "Palace of Fairies",
    desc: "7-terraced hilltop Mughal ruins with sweeping views of Dal Lake and Srinagar city.",
    images: [JKTDC_PARI],
    category: "Picnic Spots",
  },
  {
    name: "Dachigam National Park",
    tagline: "Wildlife Sanctuary",
    desc: "Sanctuary for Hangul deer, leopards, and 150+ bird species near Srinagar.",
    images: [WILD1],
    category: "Picnic Spots",
  },
  {
    name: "Shankaracharya Temple",
    tagline: "Ancient Hilltop Shrine",
    desc: "Ancient hilltop temple 1,000 ft above Dal Lake with a 360° view of Srinagar.",
    images: [MTN1],
    category: "Picnic Spots",
  },

  /* ════════════ LAKES & SPRINGS ════════════════════════════════ */
  {
    name: "Manasbal Lake",
    tagline: "Deepest Lake of Kashmir",
    desc: "Tranquil, rarely visited lake blanketed in lotus flowers and alive with migratory birds.",
    images: [LAKE1],
    category: "Lakes & Springs",
  },
  {
    name: "Wular Lake",
    tagline: "Largest Freshwater Lake in Asia",
    desc: "Asia's largest freshwater lake, a vital wetland for thousands of migratory birds.",
    images: [LAKE3],
    category: "Lakes & Springs",
  },
  {
    name: "Nagin Lake",
    tagline: "Gem of Kashmir",
    desc: "Clean and quiet lake popular for water skiing, kayaking, and peaceful houseboat stays.",
    images: [JKTDC_NAGIN],
    category: "Lakes & Springs",
  },
  {
    name: "Verinag Spring",
    tagline: "Source of the Jhelum",
    desc: "Mughal octagonal spring — birthplace of the Jhelum River, sacred and crystal clear.",
    images: [JKTDC_VERINAG],
    category: "Lakes & Springs",
  },
  {
    name: "Watlab",
    tagline: "Where Jhelum Meets Wular",
    desc: "Scenic spot where the Jhelum meets Wular Lake — known for fresh fish and beautiful sunsets.",
    images: [JKTDC_WATLAB],
    category: "Lakes & Springs",
  },
  {
    name: "Kokernag",
    tagline: "Gardens & Natural Springs",
    desc: "Famous spring gardens with trout fisheries, botanical terraces, and crystal-clear pools.",
    images: [imgKokernag],
    category: "Lakes & Springs",
  },
  {
    name: "Vishansar Lake",
    tagline: "Trekker's Alpine Lake",
    desc: "Remote alpine lake at 13,000 ft, reached by a 2-day trek from Sonamarg.",
    images: [JKTDC_VISHANSAR],
    category: "Lakes & Springs",
    highlight: "Trekking",
  },
  {
    name: "Krishnasar Lake",
    tagline: "Sacred Alpine Lake",
    desc: "Sacred alpine lake at 13,500 ft on the Sonamarg–Vishansar trek route.",
    images: [JKTDC_KRISHNASAR],
    category: "Lakes & Springs",
    highlight: "Trekking",
  },

  /* ════════════ HILL STATIONS ══════════════════════════════════ */
  {
    name: "Doodhpathri",
    tagline: "Valley of Milk",
    desc: "Emerald meadow at 8,957 ft with milky white streams — untouched and crowd-free.",
    images: [JKTDC_DOODHP],
    category: "Hill Stations",
    highlight: "Hidden Gem",
  },
  {
    name: "Bangus Valley",
    tagline: "Kashmir's Secret Valley",
    desc: "Vast twin alpine meadows in Kupwara, almost unknown to tourists — pure wilderness.",
    images: [FOR1],
    category: "Hill Stations",
    highlight: "Off-beat",
  },
  {
    name: "Lolab Valley",
    tagline: "Heaven on Earth",
    desc: "Dense deodar forests, apple orchards, and gurgling streams in a hidden Kupwara valley.",
    images: [JKTDC_LOLAB],
    category: "Hill Stations",
  },
  {
    name: "Gurez Valley",
    tagline: "Land Beyond Mountains",
    desc: "Remote valley near the LOC with dramatic peaks, the Kishanganga river, and ancient Dard culture.",
    images: [JKTDC_GUREZ],
    category: "Hill Stations",
    highlight: "Off-beat",
  },
  {
    name: "Sinthan Top",
    tagline: "Mountain Pass at 12,400 ft",
    desc: "High-altitude pass at 12,400 ft — snow in winter, wildflowers in summer, jaw-dropping views.",
    images: [JKTDC_SINTHAN],
    category: "Hill Stations",
  },
  {
    name: "Peer Ki Gali",
    tagline: "Ancient Mughal Road Pass",
    desc: "Mountain pass at 11,500 ft on the Mughal Road with wildflowers and Pir Panjal views.",
    images: [JKTDC_PEERGALI],
    category: "Hill Stations",
  },
  {
    name: "Aharbal Waterfall",
    tagline: "Niagara of Kashmir",
    desc: "Vishav River plunges 25 metres into a gorge surrounded by dense deodar forest in Shopian.",
    images: [JKTDC_AHARBAL],
    category: "Hill Stations",
    highlight: "Scenic",
  },
  {
    name: "Kounsarnag Lake",
    tagline: "Trekker's Paradise",
    desc: "Remote alpine lake at 13,000 ft, 2-day trek from Aharbal through pristine wilderness.",
    images: [imgKounsarnag],
    category: "Hill Stations",
    highlight: "Trekking",
  },
  {
    name: "Chandanwari",
    tagline: "Start of Amarnath Yatra",
    desc: "Starting point of the Amarnath Yatra at 9,500 ft, with snowfields lasting through July.",
    images: [imgChandanwari],
    category: "Hill Stations",
  },
  {
    name: "Naranag",
    tagline: "Ancient Temple & Forest Retreat",
    desc: "8th-century ruined temple complex in pine forest beside the roaring Wangath stream.",
    images: [JKTDC_NARANAG],
    category: "Hill Stations",
  },
  {
    name: "Daksum",
    tagline: "Pine-Forest Hill Station",
    desc: "Serene hill station in thick pine forests, trailhead for Sinthan Top and Kishtwar National Park.",
    images: [JKTDC_DAKSUM],
    category: "Hill Stations",
  },
  {
    name: "Warwan Valley",
    tagline: "Kashmir's Untouched Wilderness",
    desc: "One of Kashmir's most remote valleys — vast meadows and pristine scenery via Sinthan Top.",
    images: [JKTDC_WARWAN],
    category: "Hill Stations",
    highlight: "Off-beat",
  },

  /* ════════════ PILGRIMAGES ════════════════════════════════════ */
  {
    name: "Amarnath Shrine",
    tagline: "Abode of Lord Shiva",
    desc: "Holy cave shrine at 12,756 ft where a natural ice lingam of Lord Shiva forms each year.",
    images: [imgAmarnath],
    category: "Pilgrimages",
    highlight: "Sacred",
  },
  {
    name: "Vaishno Devi",
    tagline: "Mata Vaishno Devi Mandir",
    desc: "Sacred cave shrine of Mata Vaishno Devi in the Trikuta Mountains, visited by millions.",
    images: [imgVaishnoDevi],
    category: "Pilgrimages",
    highlight: "Sacred",
  },

  /* ════════════ LADAKH ═════════════════════════════════════════ */
  {
    name: "Pangong Tso",
    tagline: "Jewel of Ladakh",
    desc: "Iconic 134 km lake at 14,270 ft whose water shifts from turquoise to violet through the day.",
    images: [imgPangong],
    category: "Ladakh",
    highlight: "Iconic",
  },
  {
    name: "Nubra Valley",
    tagline: "Valley of Flowers & Sand",
    desc: "Ride Bactrian camels on sand dunes with the Karakoram range and Diskit Monastery.",
    images: [imgNubra],
    category: "Ladakh",
    highlight: "Unique",
  },
  {
    name: "Khardung La Pass",
    tagline: "One of World's Highest Roads",
    desc: "Legendary mountain pass at 17,982 ft connecting Leh to Nubra — eternal snow, thin air.",
    images: [MTN2],
    category: "Ladakh",
  },
  {
    name: "Tso Moriri",
    tagline: "Mountain Lake Sanctuary",
    desc: "Pristine lake at 15,075 ft — habitat for rare cranes and nomadic Changpa pashmina herders.",
    images: [imgTsoMoriri],
    category: "Ladakh",
  },
  {
    name: "Hemis Monastery",
    tagline: "Largest Monastery in Ladakh",
    desc: "Ladakh's wealthiest monastery, famed for its vibrant annual Cham dance festival.",
    images: [GRN1],
    category: "Ladakh",
  },
  {
    name: "Magnetic Hill",
    tagline: "Where Gravity Defies Logic",
    desc: "Gravity illusion on the Leh–Kargil highway where vehicles appear to roll uphill on their own.",
    images: [imgMagneticHill],
    category: "Ladakh",
  },
  {
    name: "Zanskar Valley",
    tagline: "Last Frontier",
    desc: "One of earth's most remote valleys, accessible in winter via the frozen Chadar River trek.",
    images: [MTN3],
    category: "Ladakh",
    highlight: "Adventure",
  },
  {
    name: "Leh City",
    tagline: "Capital of Ladakh",
    desc: "Ancient capital at 11,562 ft with Leh Palace, old monasteries, and a vibrant local market.",
    images: [ladakhImg],
    category: "Ladakh",
  },
  {
    name: "Alchi Monastery",
    tagline: "11th-Century Buddhist Art",
    desc: "Ladakh's oldest monastery with rare 11th-century murals on the banks of the Indus River.",
    images: [FOR3],
    category: "Ladakh",
  },
];

export const categories: Category[] = [
  "All",
  "Popular",
  "Picnic Spots",
  "Hill Stations",
  "Lakes & Springs",
  "Pilgrimages",
  "Ladakh",
];

export const categoryColors: Record<Exclude<Category, "All">, string> = {
  Popular: "bg-emerald-100 text-emerald-700",
  "Picnic Spots": "bg-amber-100 text-amber-700",
  "Hill Stations": "bg-blue-100 text-blue-700",
  "Lakes & Springs": "bg-cyan-100 text-cyan-700",
  Pilgrimages: "bg-orange-100 text-orange-700",
  Ladakh: "bg-violet-100 text-violet-700",
};
